In [6]:
import os
import scipy.io as sio
import os
import pickle
import numpy as np
import save_model_metadata

In [7]:

# Load data from pickle file (example):
datafile = r'\\10.99.68.52\Kiemendata\Valentina Matos\coda to python\variables\net.pkl'

with open(datafile, 'rb') as f:
    data = pickle.load(f)

WS = data['WS']
cmap = data['cmap']
classnames = data['classNames']
nm = data['nm']
umpix = data['umpix']
nwhite = data['nwhite']
pthim = data['pthim']

print(f'WS: {WS}')
print(f'classnames: {classnames}')
print(f'Cmap: {cmap}')
print(f'Umpix: {umpix}')
print(f'Nwhite: {nwhite}')
print(f'Pthim: {pthim}')


WS: [[0, 0, 0, 0, 0, 2, 0], [6, 6], [1, 2, 3, 1, 4, 5, 3], [7, 2, 3, 1, 6], 4]
classnames: ['bronchioles', 'alveoli', 'smooth_operator', 'test', 'whitespace', 'black']
Cmap: [[  0 255   0]
 [255 255   0]
 [255 128   0]
 [  0   0 255]
 [  0   0   0]]
Umpix: 2
Nwhite: 5
Pthim: \\10.99.68.52\Kiemendata\Valentina Matos\LG HG PanIN project\Jaime\Test Dashboard\5x


In [9]:
# Change paraters
umpix = 3

In [11]:
# Initialize the variable to indicate if XML reload is needed
reload_xml = 0

# Check if the pickle file exists
if not os.path.exists(datafile):
    reload_xml = 0
else:
    # Load data from the pickle file
    with open(datafile, 'rb') as f:
        data = pickle.load(f)

    # Check if variables exist in the loaded data
    if not all(key in data for key in ['WS', 'umpix', 'nwhite', 'pthim']):
        print('WS, umpix, nwhite, or pthim are missing in the pickle file. Reload the XML file to add them.')
        reload_xml = 1
    else:
        # Check if any variables have changed compared to the existing ones
        if data['WS'] != WS:
            print('Reload annotation data with updated WS.')
            reload_xml = 1
        if data['umpix'] != umpix:
            print('Reload annotation data with updated umpix.')
            reload_xml = 1
        if data['nwhite'] != nwhite:
            print('Reload annotation data with updated nwhite.')
            reload_xml = 1
        if data['pthim'] != pthim:
            print('Reload annotation data with updated pthim.')
            reload_xml = 1
            

Reload annotation data with updated umpix.
